name: Controllo API Status

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3

      - name: Controllo stato dell'API
        id: check
        continue-on-error: true
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://smal82.netsons.org/wp-json/mct/v1/classifica)
          echo "STATUS_CODE: $STATUS_CODE"
          if [ "$STATUS_CODE" -eq "200" ]; then
            echo "API ONLINE"
            echo "::set-output name=api_status::online"
            echo '{
              "schemaVersion": 1,
              "label": "API",
              "message": "online",
              "color": "brightgreen"
            }' > api-status.json
            echo "File api-status.json scritto con ONLINE"
          else
            echo "API OFFLINE"
            echo "::set-output name=api_status::offline"
            echo '{
              "schemaVersion": 1,
              "label": "API",
              "message": "offline",
              "color": "red"
            }' > api-status.json
            echo "File api-status.json scritto con OFFLINE"
          fi

      - name: Commit ad ogni controllo
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add api-status.json
          git commit -m "Aggiornato stato API"
          git push
          echo "Commit e push completati."
