name: API Status Monitor

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:  # per avviarlo manualmente se ti serve

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Controlla lo stato dell'API
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://smal82.netsons.org/wp-json/mct/v1/classifica)
          if [ "$STATUS" = "200" ]; then
            echo "✅ API ONLINE"
            echo "status=online" >> $GITHUB_OUTPUT
            echo ":white_check_mark: Online" > status.md
          else
            echo "❌ API OFFLINE"
            echo "status=offline" >> $GITHUB_OUTPUT
            echo ":x: Offline" > status.md
          fi

      - name: Commit del badge
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add status.md
          git commit -m "Aggiornato stato API"
          git push
