name: Controllo API Status

on:
  schedule:
    - cron: '*/15 * * * *'  # ogni 15 minuti
  workflow_dispatch:        # trigger manuale
  
permissions:
  contents: write  # NECESSARIO per fare commit e push

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3

      - name: Controllo stato dell'API
        id: check
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://smal82.netsons.org/wp-json/mct/v1/classifica)

          if [ "$STATUS_CODE" = "200" ]; then
            echo "API ONLINE"
            echo '{
              "schemaVersion": 1,
              "label": "API",
              "message": "online",
              "color": "brightgreen"
            }' > api-status.json
          else
            echo "API OFFLINE"
            echo '{
              "schemaVersion": 1,
              "label": "API",
              "message": "offline",
              "color": "red"
            }' > api-status.json
          fi

      - name: Commit se ci sono modifiche
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet api-status.json; then
            echo "Nessuna modifica, niente commit."
          else
            git add api-status.json
            git commit -m "Aggiornato stato API"
            git push
          fi
