name: Controllo API Status

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions: # Questa sezione definisce le autorizzazioni
  contents: read # Modificato da write a read

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3

      - name: Controllo stato dell'API
        id: check
        run: |
          HOST="smal82.netsons.org"
          PORT="443" # Assumo che la tua API sia su HTTPS, quindi porta 443. Se è HTTP, usa 80.
          TIMEOUT=5

          nc -z -w $TIMEOUT $HOST $PORT
          if [ "$?" -eq "0" ]; then
            echo "API ONLINE"
            echo "::set-output name=badge_color::green"
            echo "::set-output name=badge_message::Online"
          else
            echo "API OFFLINE"
            echo "::set-output name=badge_color::red"
            echo "::set-output name=badge_message::Offline"
          fi

      - name: Genera URL del badge
        id: badge
        run: |
          BADGE_COLOR="${{ steps.check.outputs.badge_color }}"
          BADGE_MESSAGE="${{ steps.check.outputs.badge_message }}"
          echo "::set-output name=badge_url::https://img.shields.io/badge/API-$BADGE_MESSAGE-$BADGE_COLOR"

      - name: Stampa URL del badge
        run: |
          echo "Badge URL: ${{ steps.badge.outputs.badge_url }}"
