name: Controllo API Status

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3

      - name: Controllo stato dell'API
        id: check
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://smal82.netsons.org/wp-json/mct/v1/classifica)
          echo "STATUS_CODE=$STATUS_CODE"
          if [ "$STATUS_CODE" -eq "200" ]; then
            echo "::set-output name=badge_color::green"
            echo "::set-output name=badge_message::Online"
          else
            echo "API OFFLINE"
            echo "::set-output name=badge_color::red"
            echo "::set-output name=badge_message::Offline"
          fi

      - name: Genera URL del badge
        id: badge
        run: |
          BADGE_COLOR="${{ steps.check.outputs.badge_color }}"
          BADGE_MESSAGE="${{ steps.check.outputs.badge_message }}"
          echo "::set-output name=badge_url::https://img.shields.io/badge/API-$BADGE_MESSAGE-$BADGE_COLOR"

      - name: Stampa URL del badge
        run: |
          echo "Badge URL: ${{ steps.badge.outputs.badge_url }}"
