name: Build and Package Electron App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build and Package
        uses: electron-userland/electron-builder@v4
        with:
          app-dir: . # Root of the repository
          publish: never # Change to 'always' or your preferred method for publishing releases
          win:
            target: "nsis"
          mac:
            target: "dmg"
          linux:
            target: "deb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for some packagers
