name: Build and Package Electron App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read # Permette al workflow di leggere il contenuto del repository (necessario per checkout)
  packages: write # Permette al workflow di scrivere pacchetti (potrebbe essere necessario se pubblichi)
  actions: read # Permette al workflow di leggere i log e lo stato delle azioni
  # Altre autorizzazioni specifiche di cui il tuo workflow potrebbe aver bisogno

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build and Package
        uses: electron-userland/electron-builder@v4
        with:
          app-dir: .
          publish: never
          win:
            target: "nsis"
          mac:
            target: "dmg"
          linux:
            target: "deb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
